### ISSUE TITLE
Extended ADDI instructions have incorrect mnemonic ordering

### ISSUE THREAD

**Issue by jleidel** [tactcomplabs/xbgas-tools#2]
EADDI* instructions are ordered as `eaddi* REG,IMM,REG`
They should be ordered as `eaddi* REG, REG, IMM`
This also affects the LLVM compiler, the xBGAS asm tests and the xbgas-runtime library

**Comment by BrodyWilliams** [comment]
Pushed fixes for runtime and xbgas-tools. Merge requests submitted.
